### ISSUE TITLE
AWS SES and ES config

### ISSUE THREAD

**Issue by WTM-Jarryd** [staart/api#1121] opened 2020-04-30 16:21 UTC
Hello team,

First off, thank you for the incredible project.

I am currently having an issue with the startup of a v1.0.0 api server.
It is currently running within my dev enviroment @ http://localhost:8080

The problem that I am having is that the server is not validating to the AWS SES and ES services.
I've followed the Getting Started doc to the letter.
My .env SES values are set correctly. The access id and secret key have been verified and are working as I can send mail using said credentials.

The ElasticSearch requests fail with, Error: Missing AWS credentials.

Below is the output from running staart start:
> wtm-webservices-api@1.0.0 start /home/developer/Documents/@Development/Jarryd/VueDev/Projects/SaaS/Staart/api
> staart start

✔  success   Added middleware to controllers
✔  success   Generated paths
✔  success   Processed no redirect rules
✔  success   Setup 3 cron jobs
✔  success   Serving 2 static files
✔  success   Generated app.ts file
☐  pending   Compiling TypeScript
✔  success   Listening on 8080
✔  success   Redis is working
✔  success   Redis message queue is working
✔  success   Database connection is working
✖  error     Invalid email config: Could not send a test email
⚠  warning   ElasticSearch: Unable to save record, trying again: Error: Missing AWS credentials
⚠  warning   ElasticSearch: Unable to save record, trying again: Error: Missing AWS credentials
⚠  warning   ElasticSearch: Unable to save record, trying again: Error: Missing AWS credentials
⚠  warning   ElasticSearch: Unable to save record: {"index":"staart-instances","body":{"name":"wtm-webservices-api","version":"1.0.0","repository":"git@github.com:staart/api.git","author":"Anand Chowdhary <mail@anandchowdhary.com>","staart-version":"1.3.157"}}

Where should I start looking, to debug what the SES values are at the point of the send Test email?
The SES_REGION is set the eu-west-2

Kind regards,
Jarryd
WoodTech Mechatronics

**Comment by AnandChowdhary** [comment] 2020-04-30 16:27
Thanks for opening this issue, @WTM-Jarryd. I think the problem is that I've updated the ElasticSearch plugin for Staart to work with v2, and v1 uses different environment variables. I'll make sure I fix the docs, but here's what I think might work:

The environment variables should be:

- `AWS_ELASTIC_ACCESS_KEY`
- `AWS_ELASTIC_SECRET_KEY`
- `AWS_ELASTIC_HOST`

Can you confirm that this is the case?

**Comment by WTM-Jarryd** [comment] 2020-04-30 16:42
Hi Anand,

Thanks for the swift response.

Below are my AWS config sections from my .env (ommitting the AWS credentials and ES endpoint)

ES:
## ES using AWS managed ES
AWS_ELASTIC_ACCESS_KEY = "############"
AWS_ELASTIC_SECRET_KEY = "################"
AWS_ELASTIC_HOST = "https://search-wt-webservices-es-########.eu-west-2.es.amazonaws.com"
AWS_ELASTIC_REGION = "eu-west-2"

SES:
# Sending emails via AWS SES
SES_EMAIL = "wtmweb@woodtech.biz"
SES_REGION = "eu-west-2"
SES_ACCESS = "########"
SES_SECRET = "########"

I have set these values as the default || within the src/config.ts values matching the related exports.
The changes are reflecting in the .staart/ build files.
I usually reference the config.ts keys for the .env setup.

Kind regards,
Jarryd

**Comment by WTM-Jarryd** [comment] 2020-04-30 16:54
Dependency versions for elasticsearch and mail are below:
`"@staart/elasticsearch": "^2.1.0",
"@staart/mail": "^2.0.2",`

Incase this helps.

**Comment by WTM-Jarryd** [comment] 2020-05-01 10:19
Hi Anand,

I have resolved the issue. 
It was an issue with the IAM account on AWS.
The account was initially created as an SMTP Credential account which was causing the issue.

Resolution:
Create a new user under **IAM**.
Make sure **Access Type** is set to **Programmatic Access**
Add **AmazonSESFullAccess/AmazonSESSendingAccess** and **AmazonESFullAccess** to the permission policies for SES and ElasticSearch usage. (Best done via Groups)

It is a simple issue but one that seems to cause confusion with the IAM management.

Kind regards,
Jarryd

**Comment by FindingAnand** [comment] 2020-11-09 00:10
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment] 2020-11-09 05:37
This is now fixed in v3. We don't require ElasticSearch credentials anymore and have introduced a new audit log using your database connection.

**Closed** 2020-11-09 05:36 UTC
Labels: bug, question
